### ISSUE TITLE
use passing directory for CI build 

### ISSUE THREAD

**Issue by thautwarm** [purescript-python/purescript-python#15]
the `passing` directory is a purescript-python project.

Note that we shall test all stable/latest versions through Python 3.5-3.9.

**Comment by thautwarm** [comment]
@vtheno 在干什么？有没有空？可以来加CI吗？

**Comment by vtheno** [comment]
@thautwarm 我来了我来了！

**Comment by thautwarm** [comment]
装一下0.8.2的purescripto, 然后从源码安装0.1.2的pspy-blueprint，然后就这个项目的passing directory里是一个purescript project.
你可以随便add tests。看一下`src/TestCases/*.purs`?

**Comment by thautwarm** [comment]
after installing `purescripto-0.8.2`(pip) and `pspy-blueprint`(build from source):
`cd passing && spago test`, you're supposed to pass all tests.

**Comment by vtheno** [comment]
@thautwarm 我可能得晚点弄，正在回滚系统⊂(・﹏・⊂)

**Comment by thautwarm** [comment]
done
