### ISSUE TITLE
Could have other/original licence

### ISSUE THREAD

**Issue by PallHaraldsson** [purescript-python/purescript-python#20]
>It's now under GNU LESSER GENERAL PUBLIC LICENSE.

>There're some reasons for why I have to choose this

This is the license of the compiler itself, and I just note you can choose any license for it, even if you would link statically to LGPL (but not for GPL, that's the point of the lesser/library GPL).

For the code you emit, there's the https://en.wikipedia.org/wiki/GPL_linking_exception for linking to GPL (but not needed for LGPL).

So if you really didn't want this license (I'm not saying it's bad), then you may have limited time to go back. I only noticed two commits since from others, and one was trivial, so I think can be ignored, and the other maybe, and even if it isn't it's only for tests and they could keep LGPL (or you could ask that person).

**Comment by thautwarm** [comment]
You mean it's okay to change the license to even MIT if I got the permission of @Hong-Xiang ?

Besides, thanks a lot for telling me this!

**Comment by thautwarm** [comment]
@PallHaraldsson ❤️

**Comment by thautwarm** [comment]
@Hong-Xiang Would you mind changing this repo's license to MIT?

**Comment by Hong-Xiang** [comment]
Not at all. I'm 😄 with this change.
