### ISSUE TITLE
Better debugging when lambdas are called

### ISSUE THREAD

**Issue by mikesol** [purescript-python/purescript-python#29]
I've been getting a few errors coming from lambdas being invoked correctly, and I'm having trouble debugging them. Here's one as an example:

```bash
File ".spago/simple-json/v7.0.0/src/Simple/JSON.purs", line 1, in None
    module Simple.JSON
  File ".spago/prelude/v4.1.1/src/Control/Bind.purs", line 1, in None
    module Control.Bind
  File ".spago/simple-json/v7.0.0/src/Simple/JSON.purs", line 1, in None
    module Simple.JSON
TypeError: lambda:32() takes 0 positional arguments but 1 was given
```

The actual file [JSON.py](https://github.com/purescript-python/purescript-simple-json.py/blob/master/python-ffi/Simple/JSON.py) does not have any calls to `lambda`, so my guess is that the lambda invocation happens in another file. The issue is that the name of the lambda is not descriptive enough to know where the error occurred. Running `pspy` using `pdb` does not help locate the error, either.

Any ideas for how to debug this? Thanks!

**Comment by thautwarm** [comment]
This error seems to occur when following cases happen(an incomplete list):

- finding instances for some type classes,
- defining constructors/enumerations
- binding objects to the toplevel

 An error happens in the toplevel of a module. This will always make the error looks quite weird. 

Such a confusing name(a function named `None`) is caused when constructing a function with such an AST: `AST.Function _ Nothing ...` in [Py.hs](https://github.com/purescript-python/purescript-python/blob/master/src/Language/PureScript/CodeGen/Py.hs).

To debug it, see
```
TypeError: lambda:32() takes 0 positional arguments but 1 was given
```
` lambda:32()` means a lambda in line 32, please check line 32 of `.spago/simple-json/v7.0.0/src/Simple/JSON.pur`.

**Comment by mikesol** [comment]
I checked out line 32 of JSON.purs (it's the same now in current master as it was in version 7.0.0) and it is just an import of Control.Alt: https://github.com/justinwoo/purescript-simple-json/blob/94e5e6b942209a5b7aa06b70af91544b2dbd7b43/src/Simple/JSON.purs#L32 . So I'm not sure if the `lambda` points to the right line here, but if your fix in `purescript-python` works then great!

**Comment by thautwarm** [comment]
@mikesol Okay, I can do this tomorrow.

Besides, the line 32 here seems incorrect. It's likely due to the incorrect propagation of line number.

Checking the following statements might help.

I'm planning to tentatively patch https://github.com/purescript-python/purescripto , by adding a name including the source file location to a lambda whose name is `None`.

**Comment by mikesol** [comment]
I wound up fixing this in `purescript-effect.py` and pushed the fix, so I will close this issue.
