### ISSUE TITLE
spago run does codegen

### ISSUE THREAD

**Issue by mikesol** [purescript-python/purescript-python#30]
It looks like `spago run` does codegen in addition to `spago build`. For production apps, when startup time is important, this has a negative impact. Would it be possible to limit the codegen to only `spago build`?

**Comment by thautwarm** [comment]
Actually this is not pspy-related. It's a design of spago itself.

`spago build` will run `$backend`, while `spago run` will run `$backend && $backend --run`.

You can use `pspy --run` to avoid codegen.

**Comment by mikesol** [comment]
Thanks!
