### ISSUE TITLE
Code is generated on "spago run" (expected that to happen on "spago build")

### ISSUE THREAD

**Issue by fornwall** [purescript-python/purescript-python#34]
In this sample "hello world" project: https://github.com/fornwall/purescript-python-example

We can see that running `spago run` leads to a lot of output about codegen, such as (from the `Run the python docker image` section of https://github.com/fornwall/purescript-python-example/runs/914247539?check_suite_focus=true):

```
Codegen Python for Main
Codegen Python for Effect
Codegen Python for Control.Applicative
Codegen Python for Control.Apply
[...]
```

This slows down running multiple times considerably, as each run means generating code, and I would expect the code generation to take place when running `spago build` instead.

Is there a way to move code generation to build time? Here is the Dockerfile with the steps: https://github.com/fornwall/purescript-python-example/blob/master/Dockerfile.python

**Comment by thautwarm** [comment]
Hello, `spago build` does generate python, but `spago run` will codegen python once again.
`spago build` calls

```
pspy  # codegen py
```

`spago run`  calls
```
pspy  # codegen py
pspy --run # run without codegen
```

**So far `pspy` didn't do codegen cache, so `pspy` command always does codegen.**

As a **workaround**, you can use `pspy --run` instead of `spago run`

```
spago build
pspy --run # no codegen
```

**Comment by fornwall** [comment]
Thanks a lot!

I'm closing this as I'm happy with the workaround, but feel free to reopen if you want to track the underlying problem.
