### ISSUE TITLE
Trying to run  a helloworld program, get "Backend "pspy" exited with error:2"

### ISSUE THREAD

**Issue by halloleo** [purescript-python/purescript-python#39]
I have installed `pspy` (with all the dependencies like `pspy-blueprint`) and wanted to try building a simple hello-world program. However when I execute

    spago run

I get (after lots of happy compiling) the error:

```
pspy: error: unrecognized arguments: Main.main
[error] Running failed; Backend "pspy" exited with error:2
```

**_Why's that? And how can I fix this?_**

### Details

My helloworld program is in `src/Main.purs`:

```purescript
module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "Hello World"
```

I have initialized the project with 

    spago init
    pspy --init

and added the pspy backend  to `spago.dhall`.

**Comment by thautwarm** [comment]
Older versions of spago and purescript compiler are required. The latest supported compiler is 0.13.8, but I don't have an idea of the spago version.
Besides, this project is not under maintenance.

**Comment by halloleo** [comment]
I see! Might put this on the back burner then...

Thanks a lot for getting back to me!
